app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('grupo', array('as' => 'grupo', 'uses' => 'HomeController@grupo'));
Route::get('premios', array('as' => 'premios', 'uses' => 'HomeController@premios'));
Route::get('certificacoes', array('as' => 'certificacoes', 'uses' => 'HomeController@certificacoes'));
Route::get('sustentabilidade', array('as' => 'sustentabilidade', 'uses' => 'HomeController@sustentabilidade'));
Route::get('contato', array('as' => 'contato', 'uses' => 'HomeController@contato'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'HomeController@enviar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));
Route::post('painel/login',array('as' => 'painel.login', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.logout', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('paginainicial', 'Painel\PaginaInicialController');
    Route::resource('grupo', 'Painel\GrupoController');
    Route::resource('grupomissao', 'Painel\GrupoMissaoController');
    Route::resource('premios', 'Painel\PremiosController');
    Route::resource('premiostexto', 'Painel\PremiosTextoController');
    Route::resource('certificacoes', 'Painel\CertificacoesController');
    Route::resource('certificacoesobtidas', 'Painel\CertificacoesObtidasController');
    Route::resource('sustentabilidade', 'Painel\SustentabilidadeController');
    Route::resource('sustentabilidadeacaosocial', 'Painel\SustentabilidadeAcaoSocialController');
    Route::resource('contato', 'Painel\ContatoController');
});

Route::post('ajax/gravaOrdem', array('uses' => 'Painel\AjaxController@gravaOrdem'));

app/models/GrupoMissao.php
<?php
	class GrupoMissao extends Eloquent
	{

		/**
		 * The database table used by the model.
		 *
		 * @var string
		 */
		protected $table = 'grupoempresa';

		/**
		 * The attributes excluded from the model's JSON form.
		 *
		 * @var array
		 */
		protected $hidden = array();

		// array of attributes we CAN set on the backend
	    protected $fillable = array('', 'created_at', 'updated_at');

	    // and those we CAN'T set on the backend
	    protected $guarded = array('id');

	}

app/controllers/painel/GrupoMissaoController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Hash, Thumb, File, GrupoMissao;

class GrupoMissaoController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.grupomissao.index')
		                              ->with('registros', GrupoMissao::all());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.grupomissao.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new GrupoMissao;

		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');

		try {
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto criado com sucesso.');
			return Redirect::route('painel.grupomissao.index');

		} catch (\Exception $e) {
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar texto!'));	
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.grupomissao.edit')->with('registro', GrupoMissao::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = GrupoMissao::find($id);

		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
	
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.grupomissao.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = GrupoMissao::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::route('painel.grupomissao.index');
	}

}

app/views/backend/grupomissao/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Textos da Página Inicial
        </h2>  

		{{ Form::open( array('route' => array('painel.grupomissao.update', $registro->id), 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					<label for="titulo">Título</label>
					<input type="text" class="form-control" id="titulo" autofocus name="titulo" value="{{$registro->titulo}}">
				</div>

				<div class="form-group">
					<label for="texto">Texto</label>
					<textarea class="form-control" id="texto" name="texto" >{{$registro->texto}}</textarea>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.grupomissao.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>
			</div>
		</form>
    </div>
    
@stop

app/views/backend/grupomissao/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.grupomissao.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="titulo">Título</label>
					<input type="text" class="form-control" id="titulo" autofocus name="titulo" @if(Session::has('formulario')) value="<?php $s=Session::get('formulario'); echo $s['titulo'] ?>" @endif required>
				</div>

				<div class="form-group">
					<label for="texto">Texto</label>
					<textarea class="form-control" id="texto" name="texto" s required>@if(Session::has('formulario')) value="<?php $s=Session::get('formulario'); echo $s['texto'] ?>" @endif</textarea>
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>
				<a href="{{URL::route('painel.grupomissao.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

app/views/backend/grupomissao/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Texto de Visão,Missão e Valores
        @if(count($registros)<3)
            <a href='{{ URL::route('painel.grupomissao.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Texto</a>
        @endif﻿
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='clientes'>

        <thead>
            <tr>
				<th>Título</th>
                <th>Texto</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row">
				<td>{{ $registro->titulo}}</td>
				<td>{{ $registro->texto}}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.grupomissao.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.grupomissao.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop